# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    form.media_collection.data_transformer:
        class: WellCommerce\Bundle\AppBundle\Form\DataTransformer\MediaCollectionToArrayTransformer
        tags:
            - { name: form.data_transformer, alias: media_collection }
        arguments: ['@doctrine.helper']
        shared: false

    form.media_entity.data_transformer:
        class: WellCommerce\Bundle\AppBundle\Form\DataTransformer\MediaEntityToIdentifierTransformer
        tags:
            - { name: form.data_transformer, alias: media_entity }
        arguments: ['@doctrine.helper']
        shared: false

    media.uploader:
        class: WellCommerce\Bundle\AppBundle\Service\Media\Uploader\MediaUploader
        arguments: ['@media.manager', '%kernel.root_dir%/../web/media', '@validator.helper']

    media.doctrine.event_subscriber:
        class: WellCommerce\Bundle\AppBundle\EventListener\MediaDoctrineEventSubscriber
        arguments: ["@filesystem", '%kernel.root_dir%/../web/media/images/']
        tags:
            - { name: doctrine.event_subscriber, connection: default }